// Date: 2013.06.02. 14:52:23
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package net.minecraft.src;

public class ModelDrachma extends ModelBase
{
  //fields
    ModelRenderer Part1;
    ModelRenderer Part2;
    ModelRenderer Part3;
    ModelRenderer Part4;
    ModelRenderer Part5;
    ModelRenderer Part6;
    ModelRenderer Part7;
    ModelRenderer Part8;
    ModelRenderer Part9;
    ModelRenderer Part10;
    ModelRenderer Part11;
    ModelRenderer Part12;
    ModelRenderer Part13;
    ModelRenderer Part14;
    ModelRenderer Part15;
    ModelRenderer Part16;
    ModelRenderer Part17;
    ModelRenderer Part18;
    ModelRenderer Part19;
    ModelRenderer Part20;
    ModelRenderer Part21;
    ModelRenderer Part22;
    ModelRenderer Part23;
    ModelRenderer Part24;
    ModelRenderer Part25;
    ModelRenderer Part26;
    ModelRenderer Part27;
    ModelRenderer Part28;
    ModelRenderer Part29;
    ModelRenderer Part30;
  
  public ModelDrachma()
  {
    textureWidth = 64;
    textureHeight = 64;
    
      Part1 = new ModelRenderer(this, 32, 52);
      Part1.addBox(0F, 0F, 0F, 12, 8, 4);
      Part1.setRotationPoint(0F, 0F, 0F);
      Part1.setTextureSize(64, 64);
      Part1.mirror = true;
      setRotation(Part1, 0F, 0F, 0F);
      Part2 = new ModelRenderer(this, 0, 16);
      Part2.addBox(0F, 0F, 0F, 16, 2, 2);
      Part2.setRotationPoint(-2F, -2F, 1F);
      Part2.setTextureSize(64, 64);
      Part2.mirror = true;
      setRotation(Part2, 0F, 0F, 0F);
      Part3 = new ModelRenderer(this, 0, 20);
      Part3.addBox(0F, 0F, 0F, 2, 2, 4);
      Part3.setRotationPoint(-4F, 2F, 0F);
      Part3.setTextureSize(64, 64);
      Part3.mirror = true;
      setRotation(Part3, 0F, 0F, 0F);
      Part4 = new ModelRenderer(this, 0, 26);
      Part4.addBox(0F, 0F, 0F, 2, 6, 4);
      Part4.setRotationPoint(-2F, 0F, 0F);
      Part4.setTextureSize(64, 64);
      Part4.mirror = true;
      setRotation(Part4, 0F, 0F, 0F);
      Part5 = new ModelRenderer(this, 0, 48);
      Part5.addBox(0F, 0F, 0F, 4, 12, 4);
      Part5.setRotationPoint(-6F, -10F, 0F);
      Part5.setTextureSize(64, 64);
      Part5.mirror = true;
      setRotation(Part5, 0F, 0F, 0F);
      Part6 = new ModelRenderer(this, 52, 26);
      Part6.addBox(0F, 0F, 0F, 2, 6, 4);
      Part6.setRotationPoint(12F, 0F, 0F);
      Part6.setTextureSize(64, 64);
      Part6.mirror = true;
      setRotation(Part6, 0F, 0F, 0F);
      Part7 = new ModelRenderer(this, 0, 10);
      Part7.addBox(0F, 0F, 0F, 2, 2, 4);
      Part7.setRotationPoint(14F, 2F, 0F);
      Part7.setTextureSize(64, 64);
      Part7.mirror = true;
      setRotation(Part7, 0F, 0F, 0F);
      Part8 = new ModelRenderer(this, 16, 48);
      Part8.addBox(0F, 0F, 0F, 4, 12, 4);
      Part8.setRotationPoint(14F, -10F, 0F);
      Part8.setTextureSize(64, 64);
      Part8.mirror = true;
      setRotation(Part8, 0F, 0F, 0F);
      Part9 = new ModelRenderer(this, 40, 0);
      Part9.addBox(0F, 0F, 0F, 2, 2, 2);
      Part9.setRotationPoint(-2F, -4F, 1F);
      Part9.setTextureSize(64, 64);
      Part9.mirror = true;
      setRotation(Part9, 0F, 0F, 0F);
      Part10 = new ModelRenderer(this, 40, 4);
      Part10.addBox(0F, 0F, 0F, 2, 2, 2);
      Part10.setRotationPoint(12F, -4F, 1F);
      Part10.setTextureSize(64, 64);
      Part10.mirror = true;
      setRotation(Part10, 0F, 0F, 0F);
      Part11 = new ModelRenderer(this, 12, 30);
      Part11.addBox(0F, 0F, 0F, 4, 2, 4);
      Part11.setRotationPoint(0F, -4F, 0F);
      Part11.setTextureSize(64, 64);
      Part11.mirror = true;
      setRotation(Part11, 0F, 0F, 0F);
      Part12 = new ModelRenderer(this, 12, 24);
      Part12.addBox(0F, 0F, 0F, 4, 2, 4);
      Part12.setRotationPoint(8F, -4F, 0F);
      Part12.setTextureSize(64, 64);
      Part12.mirror = true;
      setRotation(Part12, 0F, 0F, 0F);
      Part13 = new ModelRenderer(this, 48, 36);
      Part13.addBox(0F, 0F, 0F, 4, 6, 4);
      Part13.setRotationPoint(4F, -8F, 0F);
      Part13.setTextureSize(64, 64);
      Part13.mirror = true;
      setRotation(Part13, 0F, 0F, 0F);
      Part14 = new ModelRenderer(this, 28, 30);
      Part14.addBox(0F, 0F, 0F, 2, 2, 4);
      Part14.setRotationPoint(2F, -6F, 0F);
      Part14.setTextureSize(64, 64);
      Part14.mirror = true;
      setRotation(Part14, 0F, 0F, 0F);
      Part15 = new ModelRenderer(this, 28, 24);
      Part15.addBox(0F, 0F, 0F, 2, 2, 4);
      Part15.setRotationPoint(8F, -6F, 0F);
      Part15.setTextureSize(64, 64);
      Part15.mirror = true;
      setRotation(Part15, 0F, 0F, 0.0174533F);
      Part16 = new ModelRenderer(this, 48, 0);
      Part16.addBox(0F, 0F, 0F, 2, 2, 2);
      Part16.setRotationPoint(0F, -6F, 1F);
      Part16.setTextureSize(64, 64);
      Part16.mirror = true;
      setRotation(Part16, 0F, 0F, 0F);
      Part17 = new ModelRenderer(this, 48, 4);
      Part17.addBox(0F, 0F, 0F, 2, 2, 2);
      Part17.setRotationPoint(2F, -8F, 1F);
      Part17.setTextureSize(64, 64);
      Part17.mirror = true;
      setRotation(Part17, 0F, 0F, 0F);
      Part18 = new ModelRenderer(this, 28, 7);
      Part18.addBox(0F, 0F, 0F, 4, 2, 2);
      Part18.setRotationPoint(4F, -10F, 1F);
      Part18.setTextureSize(64, 64);
      Part18.mirror = true;
      setRotation(Part18, 0F, 0F, 0F);
      Part19 = new ModelRenderer(this, 56, 0);
      Part19.addBox(0F, 0F, 0F, 2, 2, 2);
      Part19.setRotationPoint(8F, -8F, 1F);
      Part19.setTextureSize(64, 64);
      Part19.mirror = true;
      setRotation(Part19, 0F, 0F, 0F);
      Part20 = new ModelRenderer(this, 56, 4);
      Part20.addBox(0F, 0F, 0F, 2, 2, 2);
      Part20.setRotationPoint(10F, -6F, 1F);
      Part20.setTextureSize(64, 64);
      Part20.mirror = true;
      setRotation(Part20, 0F, 0F, 0F);
      Part21 = new ModelRenderer(this, 0, 36);
      Part21.addBox(0F, 0F, 0F, 12, 6, 4);
      Part21.setRotationPoint(0F, -16F, 0F);
      Part21.setTextureSize(64, 64);
      Part21.mirror = true;
      setRotation(Part21, 0F, 0F, 0F);
      Part22 = new ModelRenderer(this, 40, 9);
      Part22.addBox(0F, 0F, 0F, 2, 10, 4);
      Part22.setRotationPoint(-2F, -14F, 0F);
      Part22.setTextureSize(64, 64);
      Part22.mirror = true;
      setRotation(Part22, 0F, 0F, 0F);
      Part23 = new ModelRenderer(this, 32, 36);
      Part23.addBox(0F, 0F, 0F, 2, 10, 4);
      Part23.setRotationPoint(12F, -14F, 0F);
      Part23.setTextureSize(64, 64);
      Part23.mirror = true;
      setRotation(Part23, 0F, 0F, 0F);
      Part24 = new ModelRenderer(this, 52, 20);
      Part24.addBox(0F, 0F, 0F, 2, 2, 4);
      Part24.setRotationPoint(-4F, -12F, 0F);
      Part24.setTextureSize(64, 64);
      Part24.mirror = true;
      setRotation(Part24, 0F, 0F, 0F);
      Part25 = new ModelRenderer(this, 28, 0);
      Part25.addBox(0F, 0F, 0F, 2, 2, 4);
      Part25.setRotationPoint(2F, -10F, 0F);
      Part25.setTextureSize(64, 64);
      Part25.mirror = true;
      setRotation(Part25, 0F, 0F, 0F);
      Part26 = new ModelRenderer(this, 12, 0);
      Part26.addBox(0F, 0F, 0F, 2, 4, 4);
      Part26.setRotationPoint(0F, -10F, 0F);
      Part26.setTextureSize(64, 64);
      Part26.mirror = true;
      setRotation(Part26, 0F, 0F, 0F);
      Part27 = new ModelRenderer(this, 52, 14);
      Part27.addBox(0F, 0F, 0F, 2, 2, 4);
      Part27.setRotationPoint(14F, -12F, 0F);
      Part27.setTextureSize(64, 64);
      Part27.mirror = true;
      setRotation(Part27, 0F, 0F, 0F);
      Part28 = new ModelRenderer(this, 0, 0);
      Part28.addBox(0F, 0F, 0F, 2, 2, 4);
      Part28.setRotationPoint(8F, -10F, 0F);
      Part28.setTextureSize(64, 64);
      Part28.mirror = true;
      setRotation(Part28, 0F, 0F, 0F);
      Part29 = new ModelRenderer(this, 12, 8);
      Part29.addBox(0F, 0F, 0F, 2, 4, 4);
      Part29.setRotationPoint(10F, -10F, 0F);
      Part29.setTextureSize(64, 64);
      Part29.mirror = true;
      setRotation(Part29, 0F, 0F, 0F);
      Part30 = new ModelRenderer(this, 0, 0);
      Part30.addBox(0F, 0F, 0F, 2, 4, 4);
      Part30.setRotationPoint(10F, -10F, 0F);
      Part30.setTextureSize(64, 64);
      Part30.mirror = true;
      setRotation(Part30, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5);
    Part1.render(f5);
    Part2.render(f5);
    Part3.render(f5);
    Part4.render(f5);
    Part5.render(f5);
    Part6.render(f5);
    Part7.render(f5);
    Part8.render(f5);
    Part9.render(f5);
    Part10.render(f5);
    Part11.render(f5);
    Part12.render(f5);
    Part13.render(f5);
    Part14.render(f5);
    Part15.render(f5);
    Part16.render(f5);
    Part17.render(f5);
    Part18.render(f5);
    Part19.render(f5);
    Part20.render(f5);
    Part21.render(f5);
    Part22.render(f5);
    Part23.render(f5);
    Part24.render(f5);
    Part25.render(f5);
    Part26.render(f5);
    Part27.render(f5);
    Part28.render(f5);
    Part29.render(f5);
    Part30.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5);
  }

}
